apiVersion: apps/v1
kind: Deployment
metadata:
  name: idp-app
  labels:
    app: idp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idp-app
  template:
    metadata:
      labels:
        app: idp-app
    spec:
      containers:
        - name: idp-app
          image: replicatedhq/kots-idp-example-app:latest
          imagePullPolicy: Always
          command:
            - ./example-app
          args:
            - "--listen=http://0.0.0.0:5555"
            - --issuer={{repl IdentityServiceIssuerURL }}
            - --client-id={{repl IdentityServiceClientID }}
            - --client-secret={{repl IdentityServiceClientSecret }}
            - --redirect-uri=http://{{repl ConfigOption "ingress_hostname"}}/callback
          ports:
            - containerPort: 5555
          env:
            - name: testing
              value: test123456
      hostAliases:
        - ip: 172.17.0.1
          hostnames:
            - myapp.kotsadmdevenv.com
